# Generated by Django 4.2.15 on 2024-08-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='user',
            new_name='User',
        ),
    ]
