# Generated by Django 4.2.15 on 2024-08-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_jobapplication_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='User',
            new_name='user',
        ),
    ]
